### ISSUE TITLE
Issue: User Policy not updated with adsys

### ISSUE THREAD

**Issue by selcem-artan** [ubuntu/adsys#1116] opened 2024-10-21 17:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

User policy not reflected after running "adsysctl update --all" . Sharing details through reproduce steps.

### Steps to reproduce it

1- We configured Picture URI and Picture URI (Dark) GPOs on AD using latests adsys policies. 
2- Using "adsysctl update --all" we tried to update machine&user policies. Unfortunately updated policy does not seen under applied user policy for user. Could you please comment on this problem?
![Screenshot from 2024-10-21 15-02-50](https://github.com/user-attachments/assets/d942cfae-567b-44a0-8b33-789fb50e4656)
![Screenshot from 2024-10-21 20-11-41](https://github.com/user-attachments/assets/8591f4f2-7327-46fb-9156-e5312bd78974)

```vsib7582@vinfra.tech@test-ThinkPad-X13-Yoga-Gen-1:/$ adsysctl policy applied --all

Policies from machine configuration:

- Ubuntu_OS_GPO ({C3DF87FA-B1AC-4815-98C6-448C056CD422})

    - dconf:

        - org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout: 0

    - gdm:

        - dconf/org/gnome/login-screen/banner-message-enable: true

        - dconf/org/gnome/login-screen/banner-message-text: 'Test Ubuntu Banner'

    - mount:

        - system-mounts: smb://172.20.24.2/drivers
 
Policies from user configuration:

- USR2_PFX_SMIME_EXPORT ({A82E81A6-9542-4074-9E0C-DE31B7ED2FC1})

- Default Domain Policy ({31B2F340-016D-11D2-945F-00C04FB984F9})

    - certificate:

        - autoenroll: 7

vsib7582@vinfra.tech@test-ThinkPad-X13-Yoga-Gen-1:/$
```
[VSIB7582 on Ubuntu.zip](https://github.com/user-attachments/files/17464678/VSIB7582.on.Ubuntu.zip)

### Environment
* adsys version: please run `adsysctl version`
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
adsys service logs can be acquired by running `adsysctl service cat -v`.
You can increase the amount of information displayed by increasing the verbosity level (-v) to -vv or -vvv.
```

### Application settings
Please redact/remove sensitive information:
```raw
Paste the contents of your adsys.yaml file here, if you created one.
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment] 2024-10-21 20:08
Hey, @selcem-artan! Thanks for reporting the issue. Would you mind following the guides listed on the issue template (they can be seen at the issue description right above) to provide us more info?

**Comment by selcem-artan** [comment] 2024-10-23 06:45
Environment :
```
sv-a@AEL-U4JW00XW6A:~$ adsysctl version

adsysctl 0.14.2~22.04

adsysd                  0.14.2~22.04
```
 
```
sv-a@AEL-U4JW00XW6A:~$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.5 LTS"

NAME="Ubuntu"

VERSION_ID="22.04"

VERSION="22.04.5 LTS (Jammy Jellyfish)"

VERSION_CODENAME=jammy

ID=ubuntu

ID_LIKE=debian

HOME_URL=https://www.ubuntu.com/

SUPPORT_URL=https://help.ubuntu.com/

BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/

PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy

UBUNTU_CODENAME=jammy
```

**Comment by selcem-artan** [comment] 2024-10-23 06:46
```
sv-a@AEL-U4JW00XW6A:~$ adsysctl service cat -v

INFO No configuration file: Config File "adsys" Not Found in "[/home/sv-a@vinfra.tech /etc /usr/sbin]".

We will only use the defaults, env variables or flags.

^Csv-a@AEL-U4JW00XW6A:~$
```

**Comment by denisonbarbosa** [comment] 2024-10-23 11:26
Hey, @selcem-artan. The `adsysctl service cat` command is a monitoring command, i.e. you need to run it and then run another adsysctl command in a separate terminal.

However, running `adsysctl policy update --all -vvv` still gives us the logs that we need to understand whether the policy is being applied incorrectly or if the policy is not targeted to the user specifically. Would you mind asking the user to run the command I've mentioned? You can send me the logs on MM to avoid leaking any sensitive information here.

**Comment by denisonbarbosa** [comment] 2024-11-06 10:56
As we talked about privately, I will close this issue since this is not a bug. The user wants to rely on [loopback processing](https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/loopback-processing-of-group-policy) to apply user policies and this is currently not supported on adsys. We can investigate the possibility of adding this feature later, but it is not in our plans yet.

**Closed by denisonbarbosa** 2024-11-06 10:56 UTC
Labels: bug
